
                  ##        .                  _ _               _ 
            ## ## ##       ==                 | | |             | |
         ## ## ## ##      ===               __| | |__   ___   __| |
     /""""""""""""""""\___/ ===            / _` | '_ \ / _ \ / _` |
~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~     | (_| | | | | (_) | (_| |
     \______ o          __/                \__,_|_| |_|\___/ \__,_|
       \    \        __/
        \____\______/                       Docker Host on Demand


sources: https://github.com/noisy/dockerhost-on-demand
chat/help: https://gitter.im/noisy/dockerhost-on-demand

